### ISSUE TITLE
Error on Update to 1.13.1

### ISSUE THREAD

**Issue by ghost** [MLG-Fortress/GraviTree#3]
Error on 1.13.1

https://pastebin.com/047PT8Jw

**Comment by RoboMWM** [comment]
btw pastebin is like the worst paste site with its ads and all, try hasteb.in or gist next time. Also you can paste in an issue, surrounding in three backticks

    ```stacktrace```

Anyways,  seems that method no longer exists or is replaced probably. Not sure when I'll get to looking at this though compared to other larger projects like GP.

**Comment by RoboMWM** [comment]
Did I fix this? I'm gonna guess I did.
